# Generated by Django 2.2.13 on 2020-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dpbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_comments', models.TextField()),
                ('stars', models.IntegerField(max_length=5)),
                ('comment_time', models.DateTimeField()),
            ],
        ),
    ]
