# Generated by Django 2.2.13 on 2020-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpbooks',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
